### PR TITLE
UI improvement - Add Contact Page

### LINKED ISSUE #35: Add contact page - UI improve
The UI of contact add page doesn't looks good.
It can be upgraded as the UI of login and signup screens - by using Material theme EditTexts.

[ Note: There may be better UI upgrades for this screen. One can use their own creativity. ]

### PR DESCRIPTION
**Pull request by codeDamon**
Solves #35 
Now Add contact page has material-theme components.

Screenshot:
screenshot

### CODE REVIEW

**Comment by priyalbhatewara123** [comment]
@codeDamon App crashes on opening addRelative activity. Please have a look

**Comment by codeDamon** [comment]
> @codeDamon App crashes on opening addRelative activity. Please have a look

On my device its working fine. Can you spot the error in the Logcat, why its crashing?

**Comment by priyalbhatewara123** [comment]
image

Trying to figure out.

**Comment by codeDamon** [comment]
Test it using the build apk

[app-debug.apk.zip](https://github.com/priyalbhatewara123/SHE--Live-Without-Fear/files/6011751/app-debug.apk.zip)

**Comment by priyalbhatewara123** [comment]
> Test it using the build apk
> 
> [app-debug.apk.zip](https://github.com/priyalbhatewara123/SHE--Live-Without-Fear/files/6011751/app-debug.apk.zip)

It's getting crashed as soon as I click on Add Relatives card view.

**Comment by codeDamon** [comment]
> It's getting crashed as soon as I click on Add Relatives card view.

How is it happening :(
To test why its crashing, i cloned the project again. Then run the app. Its working seamlessly fine.
Can you please send me the error photo again (this time complete error, specially starting portion)?
And also plz do try once re-cloning the project.

**Comment by codeDamon** [comment]
Don't worry. I will figure it out. Give me some time.

**Comment by priyalbhatewara123** [comment]
image

**Comment by priyalbhatewara123** [comment]
> Don't worry. I will figure it out. Give me some time.

Okay!

**Comment by codeDamon** [comment]
Check this build-apk 
[app-debug.apk.zip](https://github.com/priyalbhatewara123/SHE--Live-Without-Fear/files/6011926/app-debug.apk.zip)

I think its resolved now.

**Comment by priyalbhatewara123** [comment]
Yup , working fine now. Please push the necessary changes .

**Comment by codeDamon** [comment]
> Yup , working fine now. Please push the necessary changes .

Ok, :+1:  working on it.

**Pull request merged**
