### PR TITLE
UI siren activity

### PR DESCRIPTION
**Pull request by MayankUjawane**
Updated the siren activity.
Screenshot (30)

### CODE REVIEW

**Comment by priyalbhatewara123** [comment]
Why there are 3 commits?

**Comment by MayankUjawane** [comment]
Ma'am when I had fetched the upstream and then when I pull it to gitHub at that time it told me to commit so thats why I think it is showing this.

**Comment by MayankUjawane** [comment]
Is there any problem Ma'am ?

**Comment by priyalbhatewara123** [comment]
> Ma'am when I had fetched the upstream and then when I pull it to gitHub at that time it told me to commit so thats why I think it is showing this.

Always rebase your branch before pushing and making a PR.

**Comment by priyalbhatewara123** [comment]
Your PR is reverted @MayankUjawane 
UI doesn't retain it's state when we switch to another activity or when we run the app in background. You need to work on this and then create a new PR.

**Pull request merged**
