### PR TITLE
Search feature

### LINKED ISSUE #21: Implement the search feature in view_contacts activity
Through the search bar user can search for any particular contact. If no such contact exits than it should display "No such contact found. "

### PR DESCRIPTION
**Pull request by MayankUjawane**
Screenshot (75)

Please see this it is working in my laptop properly.

### CODE REVIEW

**Comment by priyalbhatewara123** [comment]
@MayankUjawane please send me the APK  file .

**Comment by MayankUjawane** [comment]
[app-debug.zip](https://github.com/priyalbhatewara123/SHE--Live-Without-Fear/files/6008001/app-debug.zip)

**Comment by priyalbhatewara123** [comment]
I have run this apk on my phone. Nothing happens on clicking the search bar.

**Comment by MayankUjawane** [comment]
Ma'am Please click on the search icon.

**Comment by priyalbhatewara123** [comment]
Good work @MayankUjawane ✨

**Comment by MayankUjawane** [comment]
Thank You Ma'am

**Pull request merged**
