### PR TITLE
Enhance the UI of Fake Siren Activity issue #5

### LINKED ISSUE #5: Enhance the UI of Fake Siren Activity.

### PR DESCRIPTION
**Pull request by MayankUjawane**
issue #5 solved

### CODE REVIEW

**Comment by priyalbhatewara123** [comment]
Hey! Did you check everything is working fine? Like after switching to different activity also UI is responsive?

**Comment by MayankUjawane** [comment]
Yes Ma'am

**Comment by priyalbhatewara123** [comment]
> Yes Ma'am

Okay, great!

**Comment by priyalbhatewara123** [comment]
Good work :) @MayankUjawane

**Comment by MayankUjawane** [comment]
Thank You Ma'am

**Pull request merged**
