### PR TITLE
Altered the logo colour

### PR DESCRIPTION
**Pull request by AB-san**
changed the colour as per ur wish

### CODE REVIEW

**Comment by priyalbhatewara123** [comment]
Always send screenshots of your work at the time of sending a PR. Also, never make a PR from master branch.

**Comment by AB-san** [comment]
sorry I am not yet familiar with git commands can u please explain what should i do?

**Comment by priyalbhatewara123** [comment]
Any updates?

**Comment by AB-san** [comment]
Yes mam done plz check it

**Pull request closed without merging**
