### PR TITLE
search feature added

### PR DESCRIPTION
**Pull request by MayankUjawane**
Solves Issue #21
• Now with the help of search bar user can search for any particular contact. 
• If searched contact is not in database than it displays "No such contact found".

### CODE REVIEW

**Comment by priyalbhatewara123** [comment]
Please resolve the conflicts.

**Comment by MayankUjawane** [comment]
I have resolved the conflicts.

**Comment by MayankUjawane** [comment]
Screenshot (63)
Screenshot (64)
Screenshot (65)

**Review by codeDamon — CHANGES_REQUESTED** [review]
Good job!
But there is a better approach. ListView supports filter(), that will simply filter list based on entered value. 
Database operations are heavy operations, we should always avoid them if possible.

For reference, visit this : https://www.androidhive.info/2012/09/android-adding-search-functionality-to-listview/

I know you already done lot of efforts :) for this issue.
But i think this approach is much better than db operations. Rest on @priyalbhatewara123

**Comment by priyalbhatewara123** [comment]
Hey @MayankUjawane . I downloaded zip file of your branch. It has errors in ContactListAdaptor.java file.

**Comment by MayankUjawane** [comment]
But ma'am it is showing "This branch has no conflicts"

**Comment by priyalbhatewara123** [comment]
image

No no , not conflicts. I downloaded the zip file of the whole app and it show errors.

**Comment by MayankUjawane** [comment]
Ok Ma'am I will look into this and will notify you after resolving error.

**Comment by priyalbhatewara123** [comment]
> Ok Ma'am I will look into this and will notify you after resolving error.

Are these errors on your system also? Or it's just me

**Comment by MayankUjawane** [comment]
Sorry for inconvenience Ma'am
I have solved the error, you can review it now.

**Comment by priyalbhatewara123** [comment]
> Sorry for inconvenience Ma'am
> I have solved the error, you can review it now.

Still not working :((

**Pull request closed without merging**
