### PR TITLE
Change in UI of Emergency contact list screen

### LINKED ISSUE #8: Change  list view of emergency contacts.

### PR DESCRIPTION
**Pull request by codeDamon**
Issue #8 solved

* Redesign complete list view with custom adaptor and custom layout.
* Add search view as per the proposed design.
* Add edit and delete icons with Toast messages.

Screenshot : Updated
Screenshot_demo

### CODE REVIEW

**Comment by priyalbhatewara123** [comment]
This looks amazing✨ But the right part with edit and delete button looks quite messy. Can you change that to on long press on any particular contact edit and delete option appears. If not then this is also great. Let me know otherwise I'll merge this only.✔

**Comment by codeDamon** [comment]
Yeah, I also feels the same about edit and delete buttons. I placed them there as per the design. 
Okay, I am adding an OnLongClickListener(). Then merge the PR.

**Comment by priyalbhatewara123** [comment]
> Yeah, I also feels the same about edit and delete buttons. I placed them there as per the design.
> Okay, I am adding an OnLongClickListener(). Then merge the PR.

Okay great🚀

**Comment by codeDamon** [comment]
**Remove edit and delete button to item-clicks**

* Redesign contact list layout. Remove edit and delete button.
* Replaced them with Options' menu button.
* Created onClickListener on this button.
* Created onLongClickListener to the list item
* On clicking to the menu button - PopUpMenu opens with two options 'Edit' and 'Delete'.
* On Long clicking to the list item - similar PopUpMenu opens.
* Selecting any options among these shows respective toasts

Screenshot : Updated 
Screenshot_demo

**Comment by priyalbhatewara123** [comment]
@codeDamon search feature is not working.

**Comment by codeDamon** [comment]
> @codeDamon search feature is not working.

Yeah, you said this issue is for ui.

**Comment by priyalbhatewara123** [comment]
Oh okay. I'll open another issue for this

**Comment by codeDamon** [comment]
Rest is fine?

**Comment by priyalbhatewara123** [comment]
> Rest is fine?

Perfect✨

**Pull request merged**
