### PR TITLE
issue of siren activity is resolved

### PR DESCRIPTION
**Pull request by MayankUjawane**
I have solved the issue which was occured in the last pull request.

### CODE REVIEW

**Comment by MayankUjawane** [comment]
Ma'am it is showing conflicts, now what I have to do ?

**Comment by priyalbhatewara123** [comment]
This PR has some conflicts. Please resolve and send a PR again.

**Comment by MayankUjawane** [comment]
Ma'am I have resolved the conflicts. 
Now is there any problem ma'am ?

**Comment by priyalbhatewara123** [comment]
Is the UI responsive even after closing the app and then opening it again?

**Comment by MayankUjawane** [comment]
Yes Ma'am I have solved that issue.

**Comment by MayankUjawane** [comment]
Ohh sorry Ma'am I didn't check that

**Comment by MayankUjawane** [comment]
Yes Ma'am I have checked that it is working fine.

**Comment by priyalbhatewara123** [comment]
From next time please make sure you do 1 commit per PR. 
I won't merge the PR if there will be more than 1 commit.

**Comment by MayankUjawane** [comment]
Ok Ma'am
There are 2 commits because of conflict.

**Comment by priyalbhatewara123** [comment]
@MayankUjawane UI is not updated in this PR.

**Comment by priyalbhatewara123** [comment]
XML file is still same. Only java file is changed

**Comment by priyalbhatewara123** [comment]
I have reverted this PR. Please send a fresh new PR including all the changes from UI to java file.

**Pull request merged**
