### PR TITLE
edit feature added #17

### PR DESCRIPTION
**Pull request by MayankUjawane**
• Added a activity to edit the contact details named EditContactDetails.
• Added a method in DataHandler class named updateContact to update the details in the database.
• Added a check for Name and Phone Number in EditContactDetails class for the valid inputs.

### CODE REVIEW

**Comment by MayankUjawane** [comment]
Sorry for two commits Ma'am

**Review by codeDamon — APPROVED** [review]
Good Job ! @MayankUjawane 
One point I wanna add - It would be better if we have a dialog box to edit the contact instead of a new activity. It's my point of view.
Although, you did great job.

**Comment by MayankUjawane** [comment]
Thank You
Since I want to give the same feel to the user as at the time of add contact activity that is why I have created a new Activity.

**Review by priyalbhatewara123 — COMMENTED** [review]
Hey @MayankUjawane . There's no need for an additional activity. A dialog box will do the work. Also text fields in dialog box should  have the previously entered name and number with 2 buttons "Save" and "Cancel" .

**Pull request closed without merging**
